.gitignore
src/main/java/it/gov/pagopa/common/mongo/config/MongoConfig.java
src/main/java/it/gov/pagopa/common/mongo/repository/MongoRepositoryImpl.java
src/main/java/it/gov/pagopa/merchant/repository/MerchantRepositoryExtendedImpl.java
src/main/java/it/gov/pagopa/merchant/service/merchant/MerchantDetailServiceImpl.java
src/main/java/it/gov/pagopa/merchant/service/merchant/MerchantListServiceImpl.java
src/main/java/it/gov/pagopa/merchant/service/merchant/UploadingMerchantServiceImpl.java
src/main/java/it/gov/pagopa/merchant/utils/Utilities.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java
src/test/java/it/gov/pagopa/common/mongo/MongoTestUtilitiesService.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryTestIntegrated.java
src/test/java/it/gov/pagopa/merchant/repository/MerchantRepositoryExtendedImplTest.java
src/test/java/it/gov/pagopa/merchant/service/merchant/MerchantDetailServiceTest.java
src/test/java/it/gov/pagopa/merchant/service/merchant/MerchantListServiceTest.java
src/test/java/it/gov/pagopa/merchant/service/merchant/UploadingMerchantServiceTest.java
src/test/java/it/gov/pagopa/merchant/utils/UtilitiesTest.java

* IDP-1106 findById optimize to be run on cosmosDB
* Utilities not more a Spring bean
* extending coverage

feat: IDP-1106 findById optimize to be run on cosmosDB (#24)

---

src/main/java/it/gov/pagopa/merchant/service/merchant/MerchantProcessOperationServiceImpl.java

**Description**
The purpose of this PR is to allign performance logs for the initiative delete.
**List of changes**
-  Modify performance log and info log
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**

fix: delete performance log fix

---

postman/idpay-merchant-e2e.postman_collection.json

**Description**
The purpose of this PR is to update the functional tests to add the newly created delete initiative api call.
**List of changes**
-  Updated functional tests: added "Delete initiative" api call after an initiative creation.
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**

feat: IDP 1619 adeguamento test merchant

---

src/main/java/it/gov/pagopa/merchant/service/merchant/UploadingMerchantServiceImpl.java
src/test/java/it/gov/pagopa/merchant/service/merchant/UploadingMerchantServiceTest.java

**Description**
The purpose of this PR is to allow merchant file upload even if the initiative is not published.
**List of changes**
-  Initiative published check removed
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**

fix: allow merchant file uploading

---

.github/workflows/anchore.yml
Dockerfile
pom.xml

**Description**
The purpose of this PR is to solve the vulnerabilities(CVE) with status high
**List of changes**
- Docker file
- Anchore
- Update dependencies
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**

feat: IDP-1329-i-container-devono-girare-su-utente-non-root

---

helm/values.yaml
src/main/java/it/gov/pagopa/merchant/dto/QueueInitiativeDTO.java
src/main/java/it/gov/pagopa/merchant/event/consumer/InitiativeConsumerConfig.java
src/main/java/it/gov/pagopa/merchant/repository/MerchantRepository.java
src/main/java/it/gov/pagopa/merchant/repository/MerchantRepositoryExtended.java
src/main/java/it/gov/pagopa/merchant/repository/MerchantRepositoryExtendedImpl.java
src/main/java/it/gov/pagopa/merchant/service/MerchantService.java
src/main/java/it/gov/pagopa/merchant/service/MerchantServiceImpl.java
src/main/java/it/gov/pagopa/merchant/service/merchant/MerchantUpdatingInitiativeService.java
src/main/java/it/gov/pagopa/merchant/service/merchant/MerchantUpdatingInitiativeServiceImpl.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/merchant/repository/MerchantRepositoryExtendedImplTest.java
src/test/java/it/gov/pagopa/merchant/service/MerchantServiceImplTest.java
src/test/java/it/gov/pagopa/merchant/service/merchant/MerchantUpdatingInitiativeServiceTest.java

The purpose of this PR is to allow merchant file upload even if the initiative is not published and to update the status of initiative on merchant once it is published.
- Added a consumer that triggers an event once a initiative is published, that update initiative status previously uploaded on the merchant.

fix: [IDP-1642] caricamento file merchant su iniziativa non pubblicata

---

.devops/deploy-pipelines.yml
.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/anchore.yml
.github/workflows/pr-title.yml
.github/workflows/release.yml
.releaserc.json
Dockerfile
helm/Chart.yaml
helm/values.yaml

- upgrade helmchart to 2.8.0
- update anchore action triggers (on push and workflow_dispatch)
- add proper .releaserc.json + bump to semantic-release v4
- add pull request template
- fix anchor skip steps
- fix codeowners

chore: [IDP-1722] devops fixes

---

helm/Chart.lock
helm/values.yaml

chore: devops fixes

---

.github/workflows/anchore.yml

chore: fix anchore skip step (#57)

---

Dockerfile

fix: IDP-1760 fix new critical CVE-2022-48174 (#60)

---

.devops/deploy-pipelines.yml
.github/workflows/anchore.yml
Dockerfile
helm/Chart.lock
helm/values.yaml
pom.xml
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeApiRetryable.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java
src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java

This PR includes:
- [IDP-1817](https://github.com/pagopa/idpay-merchant/pull/66)
- [IDP-1817 fix](https://github.com/pagopa/idpay-merchant/pull/69)
[IDP-1817]: https://pagopa.atlassian.net/browse/IDP-1817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Promote to UAT

---

helm/values.yaml
src/main/resources/application.yml

IDP-1958 fix merchant file upload consumer config

fix: IDP-1958 fix merchant file upload consumer config

---

helm/values.yaml
src/main/resources/application.yml

fix: IDP-1958 fix merchant file upload consumer config (#74)

---

pom.xml
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
src/test/java/it/gov/pagopa/common/mongo/DummySpringRepository.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/merchant/BaseIntegrationTest.java

fix: Release dev

---

src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java
src/main/java/it/gov/pagopa/common/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java

fix: logging intercepted method when 429 mongo occurs

---

Dockerfile
pom.xml
src/main/java/it/gov/pagopa/common/stream/StreamsHealthIndicator.java
src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/stream/StreamsHealthIndicatorTest.java

fix: Idp 2016 fix CVE

---

src/main/java/it/gov/pagopa/common/kafka/BaseKafkaConsumer.java
src/main/java/it/gov/pagopa/common/kafka/service/ErrorNotifierService.java
src/main/java/it/gov/pagopa/common/kafka/service/ErrorNotifierServiceImpl.java
src/main/java/it/gov/pagopa/common/kafka/utils/CommonUtilities.java
src/main/java/it/gov/pagopa/common/stream/service/ErrorPublisher.java
src/main/java/it/gov/pagopa/common/stream/service/ErrorPublisherImpl.java
src/main/java/it/gov/pagopa/merchant/event/consumer/MerchantFileConsumerConfig.java
src/main/java/it/gov/pagopa/merchant/service/MerchantErrorNotifierService.java
src/main/java/it/gov/pagopa/merchant/service/MerchantErrorNotifierServiceImpl.java
src/main/java/it/gov/pagopa/merchant/service/merchant/UploadingMerchantService.java
src/main/java/it/gov/pagopa/merchant/service/merchant/UploadingMerchantServiceImpl.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/common/kafka/service/ErrorNotifierServiceTest.java
src/test/java/it/gov/pagopa/common/utils/CommonUtilitiesTest.java
src/test/java/it/gov/pagopa/merchant/service/MerchantErrorNotifierServiceTest.java
src/test/java/it/gov/pagopa/merchant/service/merchant/UploadingMerchantServiceTest.java

Added management to errors from consumer

feat: IDP-1957-il-servizio-merchant-deve-gestire-comportamenti-get-verso-idpay-portal-welfare-backend-initiative

---

src/main/java/it/gov/pagopa/merchant/connector/initiative/InitiativeRestConnectorImpl.java
src/main/java/it/gov/pagopa/merchant/constants/MerchantConstants.java
src/main/java/it/gov/pagopa/merchant/service/merchant/UploadingMerchantServiceImpl.java
src/test/java/it/gov/pagopa/merchant/connector/InitiativeRestClientTest.java
src/test/java/it/gov/pagopa/merchant/service/merchant/UploadingMerchantServiceTest.java
src/test/resources/mappings/get_beneficiary_view.json

fix: IDP-1957 KO error when no initiative

---

Dockerfile
pom.xml
src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java
src/test/java/it/gov/pagopa/merchant/BaseIntegrationTest.java

fix: IDP-2196 fix Cve

---

specs/asyncapi.yml

- Added asyncapi.yml file with async queue census

chore: Idp 2525 documentazione async idpay merchant

---

.grype.yaml
Dockerfile
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
helm/values.yaml
pom.xml
src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java

- Fix docker amazoncorretto CVE
- Update dependency version
- Update helm values on DEV, UAT, PROD
[PR](https://github.com/pagopa/idpay-merchant/pull/111)

chore: Promote to Uat

---

pom.xml

chore: fix CVE

---

pom.xml

chore: promote to UAT 

---

.github/CODEOWNERS
Dockerfile
pom.xml

fix cve (#121)

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

chore: [IDP 2644] helm java_tool_options update

---

.github/CODEOWNERS
Dockerfile
pom.xml

chore: helm java_tool_options update

---

helm/values-prod.yaml
helm/values-uat.yaml

chore: promote to Main

---

.github/workflows/anchore.yml
.github/workflows/flow-docker-snapshot.yml
.github/workflows/pr-title.yml

This PR proposes to rename the branches in the github actions

chore: renamed branches in github actions

---

src/main/java/it/gov/pagopa/merchant/utils/validator/ContactValidator.java

added check that does not validate empty strings

fix: ebe 50

---

src/main/java/it/gov/pagopa/merchant/dto/pointofsales/PointOfSaleDTO.java
src/main/java/it/gov/pagopa/merchant/utils/validator/PointOfSaleValidator.java

fix: refactor name website

---

src/main/java/it/gov/pagopa/common/web/dto/ValidationErrorDetail.java
src/main/java/it/gov/pagopa/common/web/exception/ErrorManager.java
src/main/java/it/gov/pagopa/merchant/mapper/PointOfSaleDTOMapper.java
src/main/java/it/gov/pagopa/merchant/repository/PointOfSaleRepositoryExtendedImpl.java
src/main/java/it/gov/pagopa/merchant/utils/validator/PointOfSaleValidator.java
src/test/java/it/gov/pagopa/merchant/controller/PointOfSaleControllerImplTest.java
src/test/java/it/gov/pagopa/merchant/repository/PointOfSaleRepositoryExtendedImplTest.java
src/test/java/it/gov/pagopa/merchant/service/pointofsales/PointOfSaleServiceTest.java
src/test/java/it/gov/pagopa/merchant/utils/validator/ContactValidatorTest.java
src/test/java/it/gov/pagopa/merchant/utils/validator/PointOfSaleValidatorTest.java

fix: resolve issues

---

Dockerfile
pom.xml
src/main/java/it/gov/pagopa/common/web/dto/ValidationErrorDetail.java
src/main/java/it/gov/pagopa/common/web/exception/ErrorManager.java
src/main/java/it/gov/pagopa/merchant/mapper/PointOfSaleDTOMapper.java
src/main/java/it/gov/pagopa/merchant/repository/PointOfSaleRepositoryExtendedImpl.java
src/main/java/it/gov/pagopa/merchant/utils/validator/PointOfSaleValidator.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/web/exception/ErrorManagerTest.java
src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java
src/test/java/it/gov/pagopa/common/web/exception/ServiceExceptionHandlerTest.java
src/test/java/it/gov/pagopa/common/web/exception/ValidationExceptionHandlerTest.java
src/test/java/it/gov/pagopa/merchant/controller/MerchantControllerImplTest.java
src/test/java/it/gov/pagopa/merchant/controller/PointOfSaleControllerImplTest.java
src/test/java/it/gov/pagopa/merchant/controller/acquirer/AcquirerControllerImplTest.java
src/test/java/it/gov/pagopa/merchant/controller/merchant_portal/MerchantPortalMerchantControllerImplTest.java
src/test/java/it/gov/pagopa/merchant/repository/MerchantFileRepositoryExtendedImplTest.java
src/test/java/it/gov/pagopa/merchant/repository/MerchantRepositoryExtendedImplTest.java
src/test/java/it/gov/pagopa/merchant/repository/PointOfSaleRepositoryExtendedImplTest.java
src/test/java/it/gov/pagopa/merchant/service/MerchantErrorNotifierServiceTest.java
src/test/java/it/gov/pagopa/merchant/service/pointofsales/PointOfSaleServiceTest.java
src/test/java/it/gov/pagopa/merchant/utils/validator/ContactValidatorTest.java
src/test/java/it/gov/pagopa/merchant/utils/validator/PointOfSaleValidatorTest.java

Resolve CVE for spring-boot parent

fix: resolve cve

---

pom.xml
src/main/java/it/gov/pagopa/merchant/controller/PointOfSaleController.java
src/main/java/it/gov/pagopa/merchant/controller/PointOfSaleControllerImpl.java
src/main/java/it/gov/pagopa/merchant/dto/pointofsales/PointOfSaleDetailDTO.java
src/main/java/it/gov/pagopa/merchant/repository/PointOfSaleRepository.java
src/main/java/it/gov/pagopa/merchant/service/pointofsales/PointOfSaleService.java
src/main/java/it/gov/pagopa/merchant/service/pointofsales/PointOfSaleServiceImpl.java
src/test/java/it/gov/pagopa/merchant/controller/PointOfSaleControllerImplTest.java
src/test/java/it/gov/pagopa/merchant/service/pointofsales/PointOfSaleServiceTest.java

fix: [EBE-67] point of sale removed unused fields in response

---

src/main/java/it/gov/pagopa/merchant/service/pointofsales/PointOfSaleServiceImpl.java

fix: EBE-96 added error logging during user creation

---

pom.xml

This PR proposes to update tomcat dependency

fix: update tomcat version

---

src/main/java/it/gov/pagopa/merchant/mapper/PointOfSaleDTOMapper.java
src/main/java/it/gov/pagopa/merchant/model/PointOfSale.java
src/main/java/it/gov/pagopa/merchant/repository/PointOfSaleRepositoryExtendedImpl.java
src/test/java/it/gov/pagopa/merchant/mapper/PointOfSaleDTOMapperTest.java
src/test/java/it/gov/pagopa/merchant/test/fakers/PointOfSaleFaker.java

This PR proposes to remove the street number from the address modeling. This level of granularity is no longer required and it increases the chances to parse incorrectly an address.
The proposed mapping is now 1:1 with the address received by api param

fix: [EBE-187] Remove street number from models

---

src/main/java/it/gov/pagopa/merchant/constants/MerchantConstants.java
src/main/java/it/gov/pagopa/merchant/controller/MerchantController.java
src/main/java/it/gov/pagopa/merchant/controller/MerchantControllerImpl.java
src/main/java/it/gov/pagopa/merchant/dto/MerchantDetailDTO.java
src/main/java/it/gov/pagopa/merchant/exception/custom/MerchantAlreadyExistsException.java
src/main/java/it/gov/pagopa/merchant/mapper/MerchantModelToDTOMapper.java
src/main/java/it/gov/pagopa/merchant/repository/MerchantRepository.java
src/main/java/it/gov/pagopa/merchant/service/MerchantService.java
src/main/java/it/gov/pagopa/merchant/service/MerchantServiceImpl.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/merchant/controller/MerchantControllerImplTest.java
src/test/java/it/gov/pagopa/merchant/service/MerchantServiceImplTest.java

feat: promote to uat

---

pom.xml

This PR proposes to update spring boot to fix the latest cve

fix: update spring boot to v3.5.5

---

src/main/java/it/gov/pagopa/merchant/service/pointofsales/PointOfSaleServiceImpl.java
src/test/java/it/gov/pagopa/merchant/service/pointofsales/PointOfSaleServiceTest.java

- Add email value in description error

feat: EBE-211 error on duplicate email

---

src/main/java/it/gov/pagopa/merchant/dto/pointofsales/PointOfSaleDTO.java
src/main/java/it/gov/pagopa/merchant/mapper/PointOfSaleDTOMapper.java
src/main/java/it/gov/pagopa/merchant/utils/validator/PointOfSaleValidator.java

Merge dei campi website e channelWebsite. ChannelWebsite deprecato in favore di website.
Adeguata validazione campi.
Modificato PointOfSale -> Mapper,Validator e DTO.

feat: [EBE-254] - Adattamento logica per merge campi website e channelWebsite in website
